source "https://rubygems.org"
git_source(:github) { |repo| "https://github.com/#{repo}.git#" }

gem "activerecord", "~> 8.0"
gem "activesupport", "~> 8.0"
gem "pg", "~> 1.5"
gem "rack", "~> 2.2"
gem "rack-test", "~> 2.1"
gem "rspec", "~> 3.13"
gem "sinatra", "~> 3.2"
gem "sinatra-activerecord", "~> 2.0"
gem "sinatra-contrib", "~> 3.2"
gem "slim", "~> 5.2"
gem "thin", "~> 1.8"
gem "tux", "~> 0.3.0"
